### PR TITLE
add vagrant file with the initial commit of Flask source code

### PR DESCRIPTION
**Pull request by LihengGong**

### CODE REVIEW

**Comment by LihengGong** [comment]
> Are we supposed to use OS environment variables for username and password?

Thanks. Will do.

**Comment by michaelgold** [comment]
It seems the postrgres server is not working for me.

When I run:
```
vagrant up
vagrant ssh
psql
```
I get this error:
```
psql
psql: FATAL:  role "vagrant" does not exist
```

**Comment by LihengGong** [comment]
> It seems the postrgres server is not working for me.
> 
> When I run:
> 
> ```
> vagrant up
> vagrant ssh
> psql
> ```
> I get this error:
> 
> ```
> psql
> psql: FATAL:  role "vagrant" does not exist
> ```

Thanks for the question.

The default user for postgres is `postgres`.
Please try this:

```shell
sudo su - postgres
```

**Comment by michaelgold** [comment]
Thanks! It's working for me.

**Pull request merged**
